#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000
/* Audio I2S GPIOs */
#define AUDIO_I2S_GPIO_MCLK      GPIO_NUM_NC
#define AUDIO_I2S_GPIO_BCLK      GPIO_NUM_13
#define AUDIO_I2S_GPIO_WS        GPIO_NUM_11
#define AUDIO_I2S_GPIO_DIN       GPIO_NUM_12
#define AUDIO_I2S_GPIO_DOUT      GPIO_NUM_10
#define AUDIO_CODEC_PA_PIN       GPIO_NUM_9

#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_16
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_17
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR


#define BUILTIN_LED_GPIO        GPIO_NUM_1
#define BOOT_BUTTON_GPIO        GPIO_NUM_3
#define MCU_VCC_CTL             GPIO_NUM_2

#define ML307_RX_PIN GPIO_NUM_44
#define ML307_TX_PIN GPIO_NUM_42
#define ML307_DTR_PIN GPIO_NUM_45
#define ML307_RI_PIN GPIO_NUM_4

// A MCP Test: Control a lamp
#define LAMP_GPIO GPIO_NUM_18

#endif // _BOARD_CONFIG_H_
